### PR TITLE
Fix cli demo links

### PR DESCRIPTION
**Pull request by amirmolavi**
I found a [pre-commit hook for checking links](https://github.com/tcort/markdown-link-check) but it didn't work and it is not obvious to me why (I tested it on dummy links and it failed to catch them). In the meantime I fixed the links in the readme file.

### CODE REVIEW

**Comment by amirmolavi** [comment]
Hi Eric, I just realized that I could merge without  an approval. I think it might be better if you protect the main branch and only give yourself exception to be able to merge without an approval. Also I think it is good practice that if after review anything change, another round of approval is mandatory.

**Review by ericmjl — APPROVED** [review]
This works! Thanks a ton, @amirmolavi. Appreciate you helping here!

**Comment by ericmjl** [comment]
> Hi Eric, I just realized that I could merge without an approval. I think it might be better if you protect the main branch and only give yourself exception to be able to merge without an approval. Also I think it is good practice that if after review anything change, another round of approval is mandatory.

Thanks Amir, the standards you've got are higher than mine! I'm actually okay with looser controls for now. The codebase moves fast because the field is moving fast. Thanks for adhering to the honor system too -- we can stick to that for now.

**Comment by amirmolavi** [comment]
> > Hi Eric, I just realized that I could merge without an approval. I think it might be better if you protect the main branch and only give yourself exception to be able to merge without an approval. Also I think it is good practice that if after review anything change, another round of approval is mandatory.
> 
> Thanks Amir, the standards you've got are higher than mine! I'm actually okay with looser controls for now. The codebase moves fast because the field is moving fast. Thanks for adhering to the honor system too -- we can stick to that for now.

Make sense :) I will pick up another issue to work on, Also, if you can think of a task or feature that you think is more needed that current issues, please open an issue and assign it to me. I would happliy do it.

**Pull request merged**
