### PR TITLE
Update llama_index import and add kwargs support

### PR DESCRIPTION
**Pull request by RenaLu**
Two updates here:
1. Update llama_index support to be importing from `llama_index.core` instead of `llama`. This is necessary if we use an updated version of llama_index. I installed the latest version of `llama_index` which was 0.10.3, and got an import error because the import path has changed. Another option is to pin llama_index down to a version that supports the previous import path. 
2. Adding kwargs support to SimpleBot and QueryBot, so we have more flexibility with the completion_kwargs that get passed into `litellm.completion`. I can add kwargs support to the other bots in a following PR!

### CODE REVIEW

**Review by ericmjl — APPROVED** [review]
Super clean and nice PR, thank you @RenaLu!

**Comment by ericmjl** [comment]
@RenaLu thank you for your PR! I really appreciate it :smile:. As soon as I can confirm that the tests pass, I will merge and cut a patch release.

**Comment by ericmjl** [comment]
@RenaLu would you be kind enough to enable repo maintainers to push to PR branches please? I looked through the test issues and determined that it's all environment-related, and have figured out the fixes.

The LLM world is evolving so fast, it's hard to keep up!

**Comment by ericmjl** [comment]
@RenaLu it looks like the final issue left is this:

```
==================================== ERRORS ====================================
_________________ ERROR collecting tests/test_doc_processor.py _________________
ImportError while importing test module '/home/runner/work/llamabot/llamabot/tests/test_doc_processor.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_doc_processor.py:5: in <module>
    from llama_index import Document
E   ImportError: cannot import name 'Document' from 'llama_index' (unknown location)
=============================== warnings summary ===============================
```

I'm having trouble pushing to your fork, and I think it has to do with the PR coming from the `main` branch on your fork rather than a different branch name. Regardless, I think we can work around this problem :).

As it is with `doc_processor.py`, in `test_doc_processor.py`, could you change the `Document` symbol import line to be:

```python
from llama_index.core.schema import Document
```

The other issue I am seeing here is that the pre-commit hooks, which enforce code style without needing to have humans argue about style, are failing. Could you install the hooks and then run them all? The commands should roughly be:

```bash
conda activate llamabot
pre-commit install
pre-commit run --all-files
```

Following that, if there are further changes as a result of the pre-commit hooks, please go ahead and commit them.

I have a full day of meetings today, but I should be able to get back to the PR before the end of the day.

**Comment by RenaLu** [comment]
Done! Thank you for your review and your commits @ericmjl !

**Pull request merged**
